- name: Import operator for {{ operator.name }}
  when: operator.mirror
  block:
    - debug:
        msg: "Importing {{ operator.name }}"

    - name: Remove old operator mirror (v2) directories
      become: yes
      file:
        path: "{{ bundle_dir }}/v2"
        state: absent
    
    - name: Extract {{ operator.name }}
      when: operator.mirror
      unarchive:
        src: "{{ bundle_dir }}/olm-{{ ocp_release }}-{{ operator.name }}.gz"
        dest: "{{ bundle_dir }}"
    
    - name: Find manifests directory
      find:
        paths: "{{ bundle_dir }}"
        patterns: "manifests-redhat-operator-index*"
        use_regex: yes
        file_type: directory
        recurse: no
      register: manifests_dirs
    
    - name: Remove manifests directory
      when: manifests_dirs.matched > 0
      become: yes
      file:
        path: "{{ manifests_dir }}"
        state: absent
      loop: "{{ manifests_dirs.files|map(attribute='path')|list }}"
      loop_control:
        loop_var: manifests_dir
        label: "{{ manifests_dir|basename }}"
    
    - name: Create {{ operator.name }} manifest
      command: >
        oc adm catalog mirror -a {{ pullsecret }} --manifests-only -a {{ registry_secret }}
        file://mirror/{{ local_namespace }}/{{ rh_catalog_image|basename }} {{ local_registry }}/{{ local_namespace }}
      args:
        chdir: "{{ bundle_dir }}"

    - name: Find tmp file directory for {{ operator.name }}
      find:
        paths: "{{ bundle_dir }}"
        patterns: "{{ rh_catalog_image.split(':')[0]|basename }}-*"
        file_type: directory
        recurse: yes
      register: tmp_file_dir

    - name: Check that tmp file directory was found
      assert:
        that:
          - tmp_file_dir.matched == 1
        fail_msg: "Found {{ tmp_file_dir.matched }} directories, expected 1"

    - name: Save the old and new path
      set_fact:
        old_path: "{{ tmp_file_dir.files[0].path }}"
        new_path: "{{ tmp_file_dir.files[0].path|dirname }}/{{ operator.name }}"

    - name: Create new tmp manifest directory for {{ operator.name }}
      file:
        path: "{{ new_path }}"
        state: directory

    - name: Copy manifest files from old:{{ old_path|dirname }} to new:{{ new_path|dirname }}
      copy:
        src: "{{ item }}"
        dest: "{{ new_path }}"
      with_fileglob:
        - "{{ old_path }}/*"

    - name: Remove old tmp file directory
      file:
        path: "{{ old_path }}"
        state: absent

    - name: Remove extra catalog image from manifest
      lineinfile:
        path: "{{ new_path }}/mapping.txt"
        state: absent
        regexp: "{{ rh_catalog_image|basename }}"

    - name: Split the manifest file to avoid Quay issues
      command: >
        split -d -l 10 {{ new_path }}/mapping.txt {{ new_path }}/chunk.

    - name: Mirror {{ operator.name }} to registry
      command: >
        oc image mirror -a {{ registry_secret }} -f "{{ item }}" --filter-by-os='.*'
      args:
        chdir: "{{ bundle_dir }}"
      with_fileglob:
        - "{{ new_path }}/chunk.*"

    - name: Find built {{ tmp_icsp }} file
      find:
        paths: "{{ new_path }}"
        file_type: file
        patterns: "{{ tmp_icsp }}"
      register: tmp_icsp_file

    - name: Check that at least one {{ tmp_icsp }} file was found
      assert:
        that:
          - tmp_icsp_file.matched >= 1
        fail_msg: "Found {{ tmp_icsp_file.matched }} icsp file(s), there should be at least 1"

    - name: Update imageContentSourcePolicy source entries
      replace:
        path: "{{ tmp_icsp_file.files[0].path }}"
        regexp: "mirror/{{ local_namespace }}/{{ rh_catalog_image.split(':')[0]|basename }}"
        replace: 'registry.redhat.io'        

    - name: Update imageContentSourcePolicy name
      replace:
        path: "{{ tmp_icsp_file.files[0].path }}"
        regexp: "name: {{ local_namespace }}-{{ rh_catalog_image.split(':')[0]|basename }}-*"
        replace: "name: {{ rh_catalog_image.split(':')[0]|basename }}"
