---
- name: Mirror OpenShift operators
  hosts: connected

  vars:
    connected: yes

  tasks:
    - name: Mirror release from internet to disk
      when: connected|bool
      include_role:
        name: ocp-mirror
        tasks_from: mirror-to-disk.yml

    - name: Mirror release from disk to disconnected registry
      when: not connected|bool
      include_role:
        name: ocp-mirror
        tasks_from: mirror-to-registry.yml
