---
- name: Mirror OpenShift operators
  hosts: connected

  vars:
    connected: yes

  tasks:
    - name: Mirror operators from internet to disk
      when: connected
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-disk.yml

    - name: Mirror operators from disk to disconnected registry
      when: not connected
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-registry.yml
