---
- name: Mirror OpenShift operators
  hosts: "{{ run_hosts | default('connected') }}"

  vars_files:
    - vars/users.yaml

  vars:
    connected: yes

  tasks:
    - name: Mirror operators from internet to disk
      when: connected|bool
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-disk.yml

    - name: Mirror operators from disk to disconnected registry
      when: not connected|bool
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-registry.yml
