---
- name: Mirror OpenShift operators
  hosts: disconnected

  vars_files:
    - vars/users.yaml

  tasks:
    - name: Mirror operators from disk to disconnected registry
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-registry.yml
