---
- name: Mirror OpenShift operators
  hosts: registry

  tasks:
    - name: Mirror operators from disk to disconnected registry
      include_role:
        name: olm-mirror
        tasks_from: mirror-to-registry.yml
