- name: Extract the release bundle
  unarchive:
    src: "{{ bundle_file }}"
    remote_src: yes
    dest: "{{ removable_media_path }}"
    creates: "{{ removable_media_path }}/downloads/openshift-client-linux-{{ ocp_release }}.tar.gz"

- name: Install binaries for {{ ocp_release }}
  become: yes
  unarchive:
    src: "{{ removable_media_path }}/downloads/{{ item }}-linux-{{ ocp_release }}.tar.gz"
    remote_src: yes
    dest: /usr/bin
    exclude:
      - README.md
      - kubectl
  loop:
    - openshift-client
    - openshift-install

- name: Encode the registry credentials
  set_fact:
    registry_creds: "{{ registry_creds|b64encode }}"

- name: Create a pull secret using the local registry secret
  template:
    src: secret.j2 
    dest: "{{ registry_secret }}"

- name: Sync from local dir to registry
  command: >
    oc image mirror -a {{ registry_secret }} --from-dir {{ removable_media_path }}/mirror
    file://openshift/release:{{ ocp_release }}* {{ local_registry }}/{{ local_repository }}
